#!/usr/bin/env ruby

require "./mell.rb"
include Mell

def create
  Config.app_name = ARGV.length >= 2 ? ARGV[1] : nil
  Config.template_name = ARGV.length >= 3 ? ARGV[2] : nil
  Config.app_root = ARGV.length >= 4 ? ARGV[3] : "#{Dir.pwd}/gen/#{Config.app_name}"

  if Config.app_name.nil? || Config.template_name.nil?
    sintax
    return
  end

  require "#{Dir.pwd}/apps/#{Config.app_name}/main.rb"
  require "#{Dir.pwd}/templates/#{Config.template_name}/main.rb"
end

def sintax
  puts "Commands:"
  puts "\tcreate <APP_NAME> <TEMPLATE_NAME> <OUTPUT_FOLDER=./gen/app_name>"
end

def main
  if ARGV.length == 0
    sintax
    return
  end

  cmd = ARGV[0]

  if cmd == "create"
    create
  elsif cmd == "clear"
    clear
  else
    sintax
  end
end

main
